# Generated by Django 4.0.5 on 2022-06-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_floor_name_alter_room_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name_plural': 'Здание'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Сотрудник'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name_plural': 'Этаж'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name_plural': 'Кабинет'},
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Здание'),
        ),
        migrations.RemoveField(
            model_name='floor',
            name='Building',
        ),
        migrations.AddField(
            model_name='floor',
            name='Building',
            field=models.ManyToManyField(null=True, to='catalog.building'),
        ),
    ]
