# Generated by Django 4.0.5 on 2022-06-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_building_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='Building',
        ),
        migrations.AddField(
            model_name='floor',
            name='Building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.building'),
        ),
    ]
