# Generated by Django 4.0.5 on 2022-06-26 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_floor_building_floor_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='Floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.floor'),
        ),
    ]
