# Generated by Django 4.0.5 on 2022-06-26 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_building_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Floor',
            new_name='Employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Building',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Floor',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Room',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='Building',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Building',
        ),
        migrations.AddField(
            model_name='building',
            name='Employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.employee'),
        ),
        migrations.AddField(
            model_name='building',
            name='Room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.room'),
        ),
        migrations.AddField(
            model_name='floor',
            name='Employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.employee'),
        ),
        migrations.AddField(
            model_name='floor',
            name='Room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.room'),
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите номер пользователя', max_length=50)),
                ('Employee', models.ManyToManyField(null=True, to='catalog.employee')),
            ],
            options={
                'verbose_name_plural': 'Рабочее место',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='Workplace',
            field=models.ManyToManyField(null=True, to='catalog.workplace'),
        ),
    ]
