# Generated by Django 4.0.5 on 2022-06-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_employee_workplace_remove_workplace_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='name',
            field=models.CharField(default=2, max_length=200, verbose_name='Здание'),
            preserve_default=False,
        ),
    ]
