# Generated by Django 4.0.5 on 2022-06-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_floor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Employee',
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Floor'),
        ),
    ]
