# Generated by Django 4.0.5 on 2022-06-26 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_building_employee_remove_floor_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.employee'),
        ),
        migrations.AlterField(
            model_name='building',
            name='Floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.floor'),
        ),
        migrations.AlterField(
            model_name='building',
            name='Room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.room'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='Room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.room'),
        ),
    ]
