# Generated by Django 4.0.5 on 2022-06-26 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_room_employee_alter_building_floor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workplace',
        ),
        migrations.RemoveField(
            model_name='building',
            name='Floor',
        ),
        migrations.RemoveField(
            model_name='building',
            name='Room',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='Room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='Building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.building'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.floor'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.room'),
        ),
        migrations.AddField(
            model_name='floor',
            name='Building',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.building'),
        ),
        migrations.AddField(
            model_name='room',
            name='Building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.building'),
        ),
        migrations.AddField(
            model_name='room',
            name='Floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.floor'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='name',
            field=models.CharField(help_text='Введите номер этажа', max_length=15),
        ),
    ]
