# Generated by Django 4.0.5 on 2022-06-26 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_delete_workplace_remove_building_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.building'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.floor'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.room'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='Building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.building'),
        ),
        migrations.AlterField(
            model_name='room',
            name='Building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.building'),
        ),
        migrations.AlterField(
            model_name='room',
            name='Floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.floor'),
        ),
    ]
