# Generated by Django 4.0.5 on 2022-07-14 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_os_software_workstation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name_plural': 'ПО'},
        ),
        migrations.RemoveField(
            model_name='workstation',
            name='software',
        ),
        migrations.AddField(
            model_name='os',
            name='licenseKeyFile',
            field=models.FileField(blank=True, help_text='прикрепите файл', null=True, upload_to='soft/'),
        ),
        migrations.AddField(
            model_name='software',
            name='licenseKeyFile',
            field=models.FileField(blank=True, help_text='прикрепите файл', null=True, upload_to='soft/'),
        ),
        migrations.AddField(
            model_name='software',
            name='sworkstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.software'),
        ),
        migrations.AlterField(
            model_name='os',
            name='licenseKeyImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='OS/'),
        ),
        migrations.AlterField(
            model_name='software',
            name='licenseKeyImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='soft/'),
        ),
    ]
