# Generated by Django 4.0.5 on 2022-07-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_software_options_remove_workstation_software_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='sworkstation',
            new_name='workstation',
        ),
    ]
