# Generated by Django 4.0.5 on 2022-07-14 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_rename_sworkstation_software_workstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.workstation'),
        ),
    ]
