# Generated by Django 4.0.5 on 2022-07-15 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_software_workstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, help_text='Введите Название производителя', max_length=50)),
                ('name', models.CharField(help_text='Введите Название модели', max_length=50)),
                ('serial', models.CharField(blank=True, help_text='Введите серийный номер', max_length=50)),
                ('serialImg', models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='monitor/serial/')),
                ('invent', models.CharField(blank=True, help_text='Введите инвентаризационный номер', max_length=50)),
                ('inventImg', models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='monitor/invent/')),
            ],
            options={
                'verbose_name_plural': 'Монитор',
            },
        ),
        migrations.CreateModel(
            name='motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, help_text='Введите Название производителя', max_length=50)),
                ('name', models.CharField(help_text='Введите Название модели', max_length=50)),
                ('serial', models.CharField(blank=True, help_text='Введите серийный номер', max_length=50)),
                ('serialImg', models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='motherboard/soft/')),
                ('CPUSoket', models.CharField(blank=True, help_text='Описание сокета', max_length=100)),
                ('RAMSlot', models.CharField(blank=True, help_text='Описание RAM', max_length=100)),
                ('USBPort', models.CharField(blank=True, help_text='Введите количество и тип ', max_length=100)),
                ('COMPort', models.CharField(blank=True, help_text='Введите количество', max_length=100)),
                ('PCI_E', models.CharField(blank=True, help_text='Введите количество', max_length=100)),
                ('PCI', models.CharField(blank=True, help_text='Введите количество и тип', max_length=100)),
                ('VGA', models.CharField(blank=True, help_text='Введите количество', max_length=100)),
                ('SATA', models.CharField(blank=True, help_text='Введите количество', max_length=100)),
                ('HDMI', models.CharField(blank=True, help_text='Введите количество', max_length=100)),
                ('DispayPort', models.CharField(blank=True, help_text='Введите количество', max_length=100)),
                ('powerSupply', models.CharField(blank=True, help_text='Введите конфигурацию', max_length=100)),
                ('powerSupplyCPU', models.CharField(blank=True, help_text='Введите конфигурацию', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='workstation',
            name='CPU',
            field=models.TextField(blank=True, help_text='Описание CPU', max_length=100),
        ),
        migrations.AddField(
            model_name='workstation',
            name='DCPower',
            field=models.CharField(blank=True, help_text='Описание блока питания', max_length=200),
        ),
        migrations.AddField(
            model_name='workstation',
            name='GPU',
            field=models.CharField(blank=True, help_text='Описание GPU', max_length=200),
        ),
        migrations.AddField(
            model_name='workstation',
            name='HDD',
            field=models.CharField(blank=True, help_text='Описание HDD', max_length=200),
        ),
        migrations.AddField(
            model_name='workstation',
            name='RAM',
            field=models.CharField(blank=True, help_text='Описание RAM', max_length=200),
        ),
        migrations.AddField(
            model_name='workstation',
            name='SSD',
            field=models.CharField(blank=True, help_text='Описание SSD', max_length=200),
        ),
        migrations.AddField(
            model_name='workstation',
            name='invent',
            field=models.CharField(blank=True, help_text='Введите инвентаризационный номер', max_length=50),
        ),
        migrations.AddField(
            model_name='workstation',
            name='inventImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='workstation/invent/'),
        ),
        migrations.AddField(
            model_name='workstation',
            name='keyBoard',
            field=models.CharField(blank=True, help_text='Описание клавиатуры', max_length=200),
        ),
        migrations.AddField(
            model_name='workstation',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Описание производителя', max_length=200),
        ),
        migrations.AddField(
            model_name='workstation',
            name='mouse',
            field=models.CharField(blank=True, help_text='Описание мыши', max_length=200),
        ),
        migrations.AddField(
            model_name='workstation',
            name='serial',
            field=models.CharField(blank=True, help_text='Введите серийный номер', max_length=50),
        ),
        migrations.AddField(
            model_name='workstation',
            name='serialImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='workstation/serial/'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='name',
            field=models.CharField(blank=True, help_text='Введите номер станции', max_length=50),
        ),
        migrations.AddField(
            model_name='workstation',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.monitor'),
        ),
        migrations.AddField(
            model_name='workstation',
            name='motherboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.motherboard'),
        ),
    ]
