# Generated by Django 4.0.5 on 2022-07-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_monitor_motherboard_workstation_cpu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motherboard',
            options={'verbose_name_plural': 'Материнская плата'},
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='COMPort',
            field=models.TextField(blank=True, help_text='Введите количество', max_length=200),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='CPUSoket',
            field=models.TextField(blank=True, help_text='Описание сокета', max_length=200),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='DispayPort',
            field=models.TextField(blank=True, help_text='Введите количество', max_length=200),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='HDMI',
            field=models.TextField(blank=True, help_text='Введите количество', max_length=200),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='PCI',
            field=models.TextField(blank=True, help_text='Введите количество и тип', max_length=200),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='PCI_E',
            field=models.TextField(blank=True, help_text='Введите количество', max_length=200),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='RAMSlot',
            field=models.TextField(blank=True, help_text='Описание RAM', max_length=200),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='SATA',
            field=models.TextField(blank=True, help_text='Введите количество', max_length=200),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='USBPort',
            field=models.TextField(blank=True, help_text='Введите количество и тип ', max_length=200),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='VGA',
            field=models.TextField(blank=True, help_text='Введите количество', max_length=200),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='powerSupply',
            field=models.TextField(blank=True, help_text='Введите конфигурацию', max_length=200),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='powerSupplyCPU',
            field=models.TextField(blank=True, help_text='Введите конфигурацию', max_length=200),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='CPU',
            field=models.TextField(blank=True, help_text='Описание CPU', max_length=200),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='DCPower',
            field=models.TextField(blank=True, help_text='Описание блока питания', max_length=200),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='GPU',
            field=models.TextField(blank=True, help_text='Описание GPU', max_length=200),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='HDD',
            field=models.TextField(blank=True, help_text='Описание HDD', max_length=200),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='RAM',
            field=models.TextField(blank=True, help_text='Описание RAM', max_length=200),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='SSD',
            field=models.TextField(blank=True, help_text='Описание SSD', max_length=200),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='keyBoard',
            field=models.TextField(blank=True, help_text='Описание клавиатуры', max_length=200),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='mouse',
            field=models.TextField(blank=True, help_text='Описание мыши', max_length=200),
        ),
    ]
