# Generated by Django 4.0.5 on 2022-07-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_motherboard_options_alter_motherboard_comport_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['Building', 'Floor', 'name'], 'verbose_name_plural': 'Кабинет'},
        ),
        migrations.AlterModelOptions(
            name='workstation',
            options={'ordering': ['name', 'Employee', 'Workplace'], 'verbose_name_plural': 'Рабочая станция'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Building',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Floor',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Room',
        ),
        migrations.RemoveField(
            model_name='workplace',
            name='Building',
        ),
        migrations.RemoveField(
            model_name='workplace',
            name='Floor',
        ),
        migrations.AddField(
            model_name='workstation',
            name='modelComputer',
            field=models.CharField(blank=True, help_text='Введите название модели', max_length=200),
        ),
    ]
