# Generated by Django 4.0.5 on 2022-07-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_room_options_alter_workstation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name'], 'verbose_name_plural': 'Сотрудник'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['workstation', 'name'], 'verbose_name_plural': 'ПО'},
        ),
        migrations.AlterModelOptions(
            name='workplace',
            options={'ordering': ['name', 'Room'], 'verbose_name_plural': 'Рабочее место'},
        ),
        migrations.AlterModelOptions(
            name='workstation',
            options={'ordering': ['Employee', 'name', 'Workplace'], 'verbose_name_plural': 'Рабочая станция'},
        ),
        migrations.RemoveField(
            model_name='software',
            name='workstation',
        ),
        migrations.AddField(
            model_name='software',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Описание производителя', max_length=200),
        ),
        migrations.AddField(
            model_name='workstation',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.software'),
        ),
    ]
