# Generated by Django 4.0.5 on 2022-07-18 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_alter_employee_options_alter_software_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['Employee', 'workstation', 'name'], 'verbose_name_plural': 'ПО'},
        ),
        migrations.RemoveField(
            model_name='workstation',
            name='software',
        ),
        migrations.AddField(
            model_name='software',
            name='Employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.employee'),
        ),
        migrations.AddField(
            model_name='software',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.workstation'),
        ),
    ]
